import type { TechnologyItem } from '../types';

export const TECHNOLOGIES: TechnologyItem[] = [
  // Mobile Core
  {
    id: 'flutter',
    name: 'Flutter',
    category: 'mobile-core',
    categoryLabel: 'Mobile Core',
    shortDesc: 'Google\'s multi-platform UI toolkit compiling to native ARM64 machine code.',
    whatItIsUsedFor: 'Our primary framework for cross-platform Android, iOS, and desktop applications with single-codebase reliability and 60fps/120fps fluid rendering.',
    experienceLevel: 'Established Production',
    relatedService: 'Flutter App Development',
    relatedServicePath: '/services/flutter-app-development',
    relatedProject: 'SmartAgri IoT Monitor',
    relatedProjectPath: '/portfolio/smartagri-iot',
  },
  {
    id: 'dart',
    name: 'Dart',
    category: 'mobile-core',
    categoryLabel: 'Mobile Core',
    shortDesc: 'Client-optimized object-oriented language with sound null safety and JIT/AOT compilation.',
    whatItIsUsedFor: 'Strictly typed business logic, streams-based state management, asynchronous pipeline execution, and model serialization in Flutter.',
    experienceLevel: 'Established Production',
    relatedService: 'Cross-Platform Mobile Engineering',
    relatedServicePath: '/services/mobile-engineering',
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    category: 'mobile-core',
    categoryLabel: 'Mobile Core',
    shortDesc: 'Modern static-typed JVM language for native Android operating system interop.',
    whatItIsUsedFor: 'Native platform channels, background foreground services, hardware sensor bindings, and device-specific notification management.',
    experienceLevel: 'Core Discipline',
    relatedService: 'Android Platform Engineering',
    relatedServicePath: '/services/mobile-engineering',
  },
  {
    id: 'android-sdk',
    name: 'Android SDK & NDK',
    category: 'mobile-core',
    categoryLabel: 'Mobile Core',
    shortDesc: 'Google native Android toolchain, platform APIs, and hardware acceleration bridges.',
    whatItIsUsedFor: 'Deep integration with hardware sensors, camera controls, BLE peripherals, and OEM battery optimization handling.',
    experienceLevel: 'Core Discipline',
    relatedService: 'Android Platform Engineering',
    relatedServicePath: '/services/mobile-engineering',
  },

  // Web & Backend
  {
    id: 'react',
    name: 'React 18 & 19',
    category: 'web-backend',
    categoryLabel: 'Web & Backend',
    shortDesc: 'Component-driven declarative frontend library for high-performance reactive web interfaces.',
    whatItIsUsedFor: 'Interactive dashboards, enterprise client portals, real-time analytics views, and responsive web applications.',
    experienceLevel: 'Established Production',
    relatedService: 'Full-Stack Web Development',
    relatedServicePath: '/services/full-stack-web',
    relatedProject: 'Apex CRM Web Suite',
    relatedProjectPath: '/portfolio/apex-crm-suite',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'web-backend',
    categoryLabel: 'Web & Backend',
    shortDesc: 'Typed superset of JavaScript providing compile-time contract enforcement.',
    whatItIsUsedFor: 'End-to-end type safety, shared API contracts between client and server, refactoring confidence, and self-documenting codebases.',
    experienceLevel: 'Established Production',
    relatedService: 'Full-Stack Web Development',
    relatedServicePath: '/services/full-stack-web',
  },
  {
    id: 'node-js',
    name: 'Node.js & Express',
    category: 'web-backend',
    categoryLabel: 'Web & Backend',
    shortDesc: 'V8-powered asynchronous runtime for scalable network services and microservices.',
    whatItIsUsedFor: 'RESTful API servers, webhook ingestion endpoints, serverless functions, token authentication, and background task runners.',
    experienceLevel: 'Core Discipline',
    relatedService: 'Full-Stack Web Development',
    relatedServicePath: '/services/full-stack-web',
  },

  // Database & Cloud
  {
    id: 'firebase',
    name: 'Google Firebase Suite',
    category: 'database-cloud',
    categoryLabel: 'Database & Cloud',
    shortDesc: 'Comprehensive cloud ecosystem including Auth, Firestore, Cloud Functions, and Analytics.',
    whatItIsUsedFor: 'Real-time database synchronisation, zero-config OAuth/Phone authentication, secure file storage, and push notifications via FCM.',
    experienceLevel: 'Established Production',
    relatedService: 'Flutter App Development',
    relatedServicePath: '/services/flutter-app-development',
  },
  {
    id: 'sqlite',
    name: 'SQLite & Drift',
    category: 'database-cloud',
    categoryLabel: 'Database & Cloud',
    shortDesc: 'Embedded ACID-compliant transactional SQL engine running locally on-device.',
    whatItIsUsedFor: 'True offline-first data persistence, instant cache lookups without network delay, and biometric record caching.',
    experienceLevel: 'Established Production',
    relatedService: 'Cross-Platform Mobile Engineering',
    relatedServicePath: '/services/mobile-engineering',
  },
  {
    id: 'cloud-firestore',
    name: 'Cloud Firestore',
    category: 'database-cloud',
    categoryLabel: 'Database & Cloud',
    shortDesc: 'Flexible, scalable NoSQL document database for global real-time synchronization.',
    whatItIsUsedFor: 'Real-time telemetry, collaborative collaborative boards, live document state updates, and multi-tenant structured queries.',
    experienceLevel: 'Established Production',
    relatedService: 'Full-Stack Web Development',
    relatedServicePath: '/services/full-stack-web',
  },

  // Creative Tools & Animation
  {
    id: 'blender',
    name: 'Blender 3D Suite',
    category: 'creative-tools',
    categoryLabel: 'Creative & Animation Tools',
    shortDesc: 'Open-source 3D modeling, rigging, simulation, and rendering ecosystem.',
    whatItIsUsedFor: '3D character modeling, organic texturing, armature rigging, mechanical product renders, and stylized storytelling cinematography.',
    experienceLevel: 'Established Production',
    relatedService: '3D Animation & CGI Production',
    relatedServicePath: '/services/3d-animation-cgi',
    relatedProject: 'Mythos: Echoes of Bharat',
    relatedProjectPath: '/portfolio/mythos-folklore',
  },
  {
    id: 'after-effects',
    name: 'Adobe After Effects',
    category: 'creative-tools',
    categoryLabel: 'Creative & Animation Tools',
    shortDesc: 'Industry-standard motion graphics, VFX, and visual compositing platform.',
    whatItIsUsedFor: 'Motion identity systems, UI micro-interaction animation, kinetic typography, promotional video reels, and particle effect compositing.',
    experienceLevel: 'Core Discipline',
    relatedService: 'Motion Graphics & UI Animation',
    relatedServicePath: '/services/motion-graphics',
  },
  {
    id: 'premiere-pro',
    name: 'Adobe Premiere Pro',
    category: 'creative-tools',
    categoryLabel: 'Creative & Animation Tools',
    shortDesc: 'Professional non-linear video editing software for broadcast and digital media.',
    whatItIsUsedFor: 'Editorial assembly, color grading, sound design synchronization, and multi-format delivery for web, social, and commercial spots.',
    experienceLevel: 'Core Discipline',
    relatedService: '3D Animation & CGI Production',
    relatedServicePath: '/services/3d-animation-cgi',
  },
  {
    id: 'photoshop-figma',
    name: 'Photoshop & Figma',
    category: 'creative-tools',
    categoryLabel: 'Creative & Animation Tools',
    shortDesc: 'Vector design, UI prototype creation, matte painting, and asset texturing.',
    whatItIsUsedFor: 'Design systems, interactive user journey prototypes, storyboard concept art, and high-resolution texture map preparation.',
    experienceLevel: 'Core Discipline',
    relatedService: 'UI/UX Design Systems',
    relatedServicePath: '/services/ui-ux-design',
  },

  // Version Control & Tooling
  {
    id: 'git-github',
    name: 'Git & GitHub Actions',
    category: 'version-control',
    categoryLabel: 'DevOps & Tooling',
    shortDesc: 'Distributed version control with automated continuous integration and delivery pipelines.',
    whatItIsUsedFor: 'Atomic commit hygiene, automated lint and test verification, and automated build artefact generation for Android APKs and web bundles.',
    experienceLevel: 'Established Production',
    relatedService: 'Full-Stack Web Development',
    relatedServicePath: '/services/full-stack-web',
  },
];

export const TECH_CATEGORIES = [
  { id: 'all', label: 'All Technologies' },
  { id: 'mobile-core', label: 'Mobile Core' },
  { id: 'web-backend', label: 'Web & Backend' },
  { id: 'database-cloud', label: 'Database & Cloud' },
  { id: 'creative-tools', label: 'Creative & Animation' },
  { id: 'version-control', label: 'DevOps & Tooling' },
] as const;
